<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="ExDoc v0.34.2">
    <meta name="project" content="Elixir v1.17.3">


    <title>try, catch, and rescue — Elixir v1.17.3</title>
    <link rel="stylesheet" href="dist/html-elixir-F2VRIOKR.css" />


      <link rel="canonical" href="https://hexdocs.pm/elixir/try-catch-and-rescue.html" />

    <script src="dist/handlebars.runtime-NWIB6V2M.js"></script>
    <script src="dist/handlebars.templates-K7URE6B4.js"></script>
    <script src="dist/sidebar_items-3D721A5F.js"></script>
    <script src="docs_config.js"></script>
    <script async src="dist/html-YIPIRHGU.js"></script>

  </head>
  <body data-type="extras" class="page-extra">
    <script>

      try {
        var settings = JSON.parse(localStorage.getItem('ex_doc:settings') || '{}');

        if (settings.theme === 'dark' ||
           ((settings.theme === 'system' || settings.theme == null) &&
             window.matchMedia('(prefers-color-scheme: dark)').matches)
           ) {
          document.body.classList.add('dark')
        }
      } catch (error) { }
    </script>

<div class="body-wrapper">

<button id="sidebar-menu" class="sidebar-button sidebar-toggle" aria-label="toggle sidebar" aria-controls="sidebar">
  <i class="ri-menu-line ri-lg" title="Collapse/expand sidebar"></i>
</button>

<nav id="sidebar" class="sidebar">

  <div class="sidebar-header">
    <div class="sidebar-projectInfo">

        <a href="https://elixir-lang.org/docs.html" class="sidebar-projectImage">
          <img src="assets/logo.png" alt="Elixir" />
        </a>

      <div>
        <a href="https://elixir-lang.org/docs.html" class="sidebar-projectName" translate="no">
Elixir
        </a>
        <div class="sidebar-projectVersion" translate="no">
          v1.17.3
        </div>
      </div>
    </div>
    <ul id="sidebar-listNav" class="sidebar-listNav" role="tablist">
      <li>
        <button id="extras-list-tab-button" role="tab" data-type="extras" aria-controls="extras-tab-panel" aria-selected="true" tabindex="0">
Pages
        </button>
      </li>

        <li>
          <button id="modules-list-tab-button" role="tab" data-type="modules" aria-controls="modules-tab-panel" aria-selected="false" tabindex="-1">
            Modules
          </button>
        </li>


    </ul>
  </div>

  <div id="extras-tab-panel" class="sidebar-tabpanel" role="tabpanel" aria-labelledby="extras-list-tab-button">
    <ul id="extras-full-list" class="full-list"></ul>
  </div>

    <div id="modules-tab-panel" class="sidebar-tabpanel" role="tabpanel" aria-labelledby="modules-list-tab-button" hidden>
      <ul id="modules-full-list" class="full-list"></ul>
    </div>


</nav>

<main class="content">
  <output role="status" id="toast"></output>

  <div id="content" class="content-inner">
    <div class="top-search">
      <div class="search-settings">
        <form class="search-bar" action="search.html">
          <label class="search-label">
            <span class="sr-only">Search documentation of Elixir</span>
            <input name="q" type="text" class="search-input" placeholder="Press / to search" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
          </label>
          <button type="submit" class="search-button" aria-label="Submit Search">
            <i class="ri-search-2-line ri-lg" aria-hidden="true" title="Submit search"></i>
          </button>
          <button type="button" tabindex="-1" class="search-close-button" aria-hidden="true">
            <i class="ri-close-line ri-lg" title="Cancel search"></i>
          </button>
        </form>
        <div class="autocomplete">
        </div>
        <button class="icon-settings display-settings">
          <i class="ri-settings-3-line"></i>
          <span class="sr-only">Settings</span>
        </button>
      </div>
    </div>

<div id="top-content">
  <h1>

      <a href="https://github.com/elixir-lang/elixir/blob/v1.17.3/lib/elixir/pages/getting-started/try-catch-and-rescue.md#L1" title="View Source" class="icon-action" rel="help">
        <i class="ri-code-s-slash-line" aria-hidden="true"></i>
        <span class="sr-only">View Source</span>
      </a>


    <span>try, catch, and rescue</span>
  </h1>

<p>Elixir has three error mechanisms: errors, throws, and exits. In this chapter, we will explore each of them and include remarks about when each should be used.</p><h2 id="errors" class="section-heading">
  <a href="#errors" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Errors</span>
</h2>
<p>Errors (or <em>exceptions</em>) are used when exceptional things happen in the code. A sample error can be retrieved by trying to add a number to an atom:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="ss">:foo</span><span class="w"> </span><span class="o">+</span><span class="w"> </span><span class="mi">1</span><span class="w">
</span><span class="gt">** (ArithmeticError) bad argument in arithmetic expression
     :erlang.+(:foo, 1)</span></code></pre><p>A runtime error can be raised any time by using <a href="Kernel.html#raise/1"><code class="inline">raise/1</code></a>:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops&quot;</span><span class="w">
</span><span class="gt">** (RuntimeError) oops</span></code></pre><p>Other errors can be raised with <a href="Kernel.html#raise/2"><code class="inline">raise/2</code></a> passing the error name and a list of keyword arguments:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">raise</span><span class="w"> </span><span class="nc">ArgumentError</span><span class="p">,</span><span class="w"> </span><span class="ss">message</span><span class="p">:</span><span class="w"> </span><span class="s">&quot;invalid argument foo&quot;</span><span class="w">
</span><span class="gt">** (ArgumentError) invalid argument foo</span></code></pre><p>You can also define your own errors by creating a module and using the <a href="Kernel.html#defexception/1"><code class="inline">defexception/1</code></a> construct inside it. This way, you'll create an error with the same name as the module it's defined in. The most common case is to define a custom exception with a message field:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="kd">defmodule</span><span class="w"> </span><span class="nc">MyError</span><span class="w"> </span><span class="k" data-group-id="0371003479-1">do</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="w">  </span><span class="kd">defexception</span><span class="w"> </span><span class="ss">message</span><span class="p">:</span><span class="w"> </span><span class="s">&quot;default message&quot;</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k" data-group-id="0371003479-1">end</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k">raise</span><span class="w"> </span><span class="nc">MyError</span><span class="w">
</span><span class="gt">** (MyError) default message</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k">raise</span><span class="w"> </span><span class="nc">MyError</span><span class="p">,</span><span class="w"> </span><span class="ss">message</span><span class="p">:</span><span class="w"> </span><span class="s">&quot;custom message&quot;</span><span class="w">
</span><span class="gt">** (MyError) custom message</span></code></pre><p>Errors can be <strong>rescued</strong> using the <code class="inline">try/rescue</code> construct:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="3300678375-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="3300678375-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">e</span><span class="w"> </span><span class="ow">in</span><span class="w"> </span><span class="nc">RuntimeError</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="n">e</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="3300678375-1">end</span><span class="w">
</span><span class="p" data-group-id="3300678375-2">%</span><span class="nc" data-group-id="3300678375-2">RuntimeError</span><span class="p" data-group-id="3300678375-2">{</span><span class="ss">message</span><span class="p">:</span><span class="w"> </span><span class="s">&quot;oops&quot;</span><span class="p" data-group-id="3300678375-2">}</span></code></pre><p>The example above rescues the runtime error and returns the exception itself, which is then printed in the <code class="inline">iex</code> session.</p><p>If you don't have any use for the exception, you don't have to pass a variable to <code class="inline">rescue</code>:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="2744234552-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="2744234552-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">RuntimeError</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="s">&quot;Error!&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="2744234552-1">end</span><span class="w">
</span><span class="s">&quot;Error!&quot;</span></code></pre><p>In practice, Elixir developers rarely use the <code class="inline">try/rescue</code> construct. For example, many languages would force you to rescue an error when a file cannot be opened successfully. Elixir instead provides a <a href="File.html#read/1"><code class="inline">File.read/1</code></a> function which returns a tuple containing information about whether the file was opened successfully:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="9918163879-1">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="9918163879-1">)</span><span class="w">
</span><span class="p" data-group-id="9918163879-2">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="ss">:enoent</span><span class="p" data-group-id="9918163879-2">}</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">write</span><span class="p" data-group-id="9918163879-3">(</span><span class="s">&quot;hello&quot;</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;world&quot;</span><span class="p" data-group-id="9918163879-3">)</span><span class="w">
</span><span class="ss">:ok</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="9918163879-4">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="9918163879-4">)</span><span class="w">
</span><span class="p" data-group-id="9918163879-5">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;world&quot;</span><span class="p" data-group-id="9918163879-5">}</span></code></pre><p>There is no <code class="inline">try/rescue</code> here. In case you want to handle multiple outcomes of opening a file, you can use pattern matching using the <code class="inline">case</code> construct:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">case</span><span class="w"> </span><span class="nc">File</span><span class="o">.</span><span class="n">read</span><span class="p" data-group-id="6973280149-1">(</span><span class="s">&quot;hello&quot;</span><span class="p" data-group-id="6973280149-1">)</span><span class="w"> </span><span class="k" data-group-id="6973280149-2">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="p" data-group-id="6973280149-3">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="n">body</span><span class="p" data-group-id="6973280149-3">}</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="nc">IO</span><span class="o">.</span><span class="n">puts</span><span class="p" data-group-id="6973280149-4">(</span><span class="s">&quot;Success: </span><span class="si" data-group-id="6973280149-5">#{</span><span class="n">body</span><span class="si" data-group-id="6973280149-5">}</span><span class="s">&quot;</span><span class="p" data-group-id="6973280149-4">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="p" data-group-id="6973280149-6">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="n">reason</span><span class="p" data-group-id="6973280149-6">}</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="nc">IO</span><span class="o">.</span><span class="n">puts</span><span class="p" data-group-id="6973280149-7">(</span><span class="s">&quot;Error: </span><span class="si" data-group-id="6973280149-8">#{</span><span class="n">reason</span><span class="si" data-group-id="6973280149-8">}</span><span class="s">&quot;</span><span class="p" data-group-id="6973280149-7">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="6973280149-2">end</span></code></pre><p>For the cases where you do expect a file to exist (and the lack of that file is truly an <em>error</em>) you may use <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a>:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="nc">File</span><span class="o">.</span><span class="n">read!</span><span class="p" data-group-id="6253694461-1">(</span><span class="s">&quot;unknown&quot;</span><span class="p" data-group-id="6253694461-1">)</span><span class="w">
</span><span class="gt">** (File.Error) could not read file &quot;unknown&quot;: no such file or directory
    (elixir) lib/file.ex:272: File.read!/1</span></code></pre><p>At the end of the day, it's up to your application to decide if an error while opening a file is exceptional or not. That's why Elixir doesn't impose exceptions on <a href="File.html#read/1"><code class="inline">File.read/1</code></a> and many other functions. Instead, it leaves it up to the developer to choose the best way to proceed.</p><p>Many functions in the standard library follow the pattern of having a counterpart that raises an exception instead of returning tuples to match against. The convention is to create a function (<code class="inline">foo</code>) which returns <code class="inline">{:ok, result}</code> or <code class="inline">{:error, reason}</code> tuples and another function (<code class="inline">foo!</code>, same name but with a trailing <code class="inline">!</code>) that takes the same arguments as <code class="inline">foo</code> but which raises an exception if there's an error. <code class="inline">foo!</code> should return the result (not wrapped in a tuple) if everything goes fine. The <a href="File.html"><code class="inline">File</code></a> module is a good example of this convention.</p><h3 id="fail-fast-let-it-crash" class="section-heading">
  <a href="#fail-fast-let-it-crash" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Fail fast / Let it crash</span>
</h3>
<p>One saying that is common in the Erlang community, as well as Elixir's, is &quot;fail fast&quot; / &quot;let it crash&quot;. The idea behind let it crash is that, in case something <em>unexpected</em> happens, it is best to let the exception happen, without rescuing it.</p><p>It is important to emphasize the word <em>unexpected</em>. For example, imagine you are building a script to process files. Your script receives filenames as inputs. It is expected that users may make mistakes and provide unknown filenames. In this scenario, while you could use <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a> to read files and let it crash in case of invalid filenames, it probably makes more sense to use <a href="File.html#read/1"><code class="inline">File.read/1</code></a> and provide users of your script with a clear and precise feedback of what went wrong.</p><p>Other times, you may fully expect a certain file to exist, and in case it does not, it means something terribly wrong has happened elsewhere. In such cases, <a href="File.html#read!/1"><code class="inline">File.read!/1</code></a> is all you need.</p><p>The second approach also works because, as discussed in the <a href="processes.html">Processes</a> chapter, all Elixir code runs inside processes that are isolated and don't share anything by default. Therefore, an unhandled exception in a process will never crash or corrupt the state of another process. This allows us to define supervisor processes, which are meant to observe when a process terminates unexpectedly, and start a new one in its place.</p><p>At the end of the day, &quot;fail fast&quot; / &quot;let it crash&quot; is a way of saying that, when <em>something unexpected</em> happens, it is best to start from scratch within a new process, freshly started by a supervisor, rather than blindly trying to rescue all possible error cases without the full context of when and how they can happen.</p><h3 id="reraise" class="section-heading">
  <a href="#reraise" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Reraise</span>
</h3>
<p>While we generally avoid using <code class="inline">try/rescue</code> in Elixir, one situation where we may want to use such constructs is for observability/monitoring. Imagine you want to log that something went wrong, you could do:</p><pre><code class="makeup elixir" translate="no"><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="5362012406-1">do</span><span class="w">
  </span><span class="n">...</span><span class="w"> </span><span class="n">some</span><span class="w"> </span><span class="n">code</span><span class="w"> </span><span class="n">...</span><span class="w">
</span><span class="k" data-group-id="5362012406-1">rescue</span><span class="w">
  </span><span class="n">e</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
    </span><span class="nc">Logger</span><span class="o">.</span><span class="n">error</span><span class="p" data-group-id="5362012406-2">(</span><span class="nc">Exception</span><span class="o">.</span><span class="n">format</span><span class="p" data-group-id="5362012406-3">(</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="n">e</span><span class="p">,</span><span class="w"> </span><span class="c">__STACKTRACE__</span><span class="p" data-group-id="5362012406-3">)</span><span class="p" data-group-id="5362012406-2">)</span><span class="w">
    </span><span class="n">reraise</span><span class="w"> </span><span class="n">e</span><span class="p">,</span><span class="w"> </span><span class="c">__STACKTRACE__</span><span class="w">
</span><span class="k" data-group-id="5362012406-1">end</span></code></pre><p>In the example above, we rescued the exception, logged it, and then re-raised it. We use the <code class="inline">__STACKTRACE__</code> construct both when formatting the exception and when re-raising. This ensures we reraise the exception as is, without changing value or its origin.</p><p>Generally speaking, we take errors in Elixir literally: they are reserved for unexpected and/or exceptional situations, never for controlling the flow of our code. In case you actually need flow control constructs, <em>throws</em> should be used. That's what we are going to see next.</p><h2 id="throws" class="section-heading">
  <a href="#throws" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Throws</span>
</h2>
<p>In Elixir, a value can be thrown and later be caught. <code class="inline">throw</code> and <code class="inline">catch</code> are reserved for situations where it is not possible to retrieve a value unless by using <code class="inline">throw</code> and <code class="inline">catch</code>.</p><p>Those situations are quite uncommon in practice except when interfacing with libraries that do not provide a proper API. For example, let's imagine the <a href="Enum.html"><code class="inline">Enum</code></a> module did not provide any API for finding a value and that we needed to find the first multiple of 13 in a list of numbers:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="1503269214-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">Enum</span><span class="o">.</span><span class="n">each</span><span class="p" data-group-id="1503269214-2">(</span><span class="o">-</span><span class="mi">50</span><span class="o">..</span><span class="mi">50</span><span class="p">,</span><span class="w"> </span><span class="k" data-group-id="1503269214-3">fn</span><span class="w"> </span><span class="n">x</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="k">if</span><span class="w"> </span><span class="n">rem</span><span class="p" data-group-id="1503269214-4">(</span><span class="n">x</span><span class="p">,</span><span class="w"> </span><span class="mi">13</span><span class="p" data-group-id="1503269214-4">)</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="mi">0</span><span class="p">,</span><span class="w"> </span><span class="ss">do</span><span class="p">:</span><span class="w"> </span><span class="k">throw</span><span class="p" data-group-id="1503269214-5">(</span><span class="n">x</span><span class="p" data-group-id="1503269214-5">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k" data-group-id="1503269214-3">end</span><span class="p" data-group-id="1503269214-2">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="s">&quot;Got nothing&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="1503269214-1">catch</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">x</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="s">&quot;Got </span><span class="si" data-group-id="1503269214-6">#{</span><span class="n">x</span><span class="si" data-group-id="1503269214-6">}</span><span class="s">&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="1503269214-1">end</span><span class="w">
</span><span class="s">&quot;Got -39&quot;</span></code></pre><p>Since <a href="Enum.html"><code class="inline">Enum</code></a> <em>does</em> provide a proper API, in practice <a href="Enum.html#find/2"><code class="inline">Enum.find/2</code></a> is the way to go:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="nc">Enum</span><span class="o">.</span><span class="n">find</span><span class="p" data-group-id="5986065466-1">(</span><span class="o">-</span><span class="mi">50</span><span class="o">..</span><span class="mi">50</span><span class="p">,</span><span class="w"> </span><span class="o">&amp;</span><span class="p" data-group-id="5986065466-2">(</span><span class="n">rem</span><span class="p" data-group-id="5986065466-3">(</span><span class="ni">&amp;1</span><span class="p">,</span><span class="w"> </span><span class="mi">13</span><span class="p" data-group-id="5986065466-3">)</span><span class="w"> </span><span class="o">==</span><span class="w"> </span><span class="mi">0</span><span class="p" data-group-id="5986065466-2">)</span><span class="p" data-group-id="5986065466-1">)</span><span class="w">
</span><span class="o">-</span><span class="mi">39</span></code></pre><h2 id="exits" class="section-heading">
  <a href="#exits" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Exits</span>
</h2>
<p>All Elixir code runs inside processes that communicate with each other. When a process dies of &quot;natural causes&quot; (e.g., unhandled exceptions), it sends an <code class="inline">exit</code> signal. A process can also die by explicitly sending an <code class="inline">exit</code> signal:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="n">spawn_link</span><span class="p" data-group-id="9122455324-1">(</span><span class="k" data-group-id="9122455324-2">fn</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="n">exit</span><span class="p" data-group-id="9122455324-3">(</span><span class="mi">1</span><span class="p" data-group-id="9122455324-3">)</span><span class="w"> </span><span class="k" data-group-id="9122455324-2">end</span><span class="p" data-group-id="9122455324-1">)</span><span class="w">
</span><span class="gt">** (EXIT from #PID&lt;0.56.0&gt;) shell process exited with reason: 1</span></code></pre><p>In the example above, the linked process died by sending an <code class="inline">exit</code> signal with a value of 1. The Elixir shell automatically handles those messages and prints them to the terminal.</p><p><code class="inline">exit</code> can also be &quot;caught&quot; using <code class="inline">try/catch</code>:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="8879753672-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">exit</span><span class="p" data-group-id="8879753672-2">(</span><span class="s">&quot;I am exiting&quot;</span><span class="p" data-group-id="8879753672-2">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="8879753672-1">catch</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="ss">:exit</span><span class="p">,</span><span class="w"> </span><span class="bp">_</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="s">&quot;not really&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="8879753672-1">end</span><span class="w">
</span><span class="s">&quot;not really&quot;</span></code></pre><p><code class="inline">catch</code> can also be used within a function body without a matching <code class="inline">try</code>.</p><pre><code class="makeup elixir" translate="no"><span class="kd">defmodule</span><span class="w"> </span><span class="nc">Example</span><span class="w"> </span><span class="k" data-group-id="7163761830-1">do</span><span class="w">
  </span><span class="kd">def</span><span class="w"> </span><span class="nf">matched_catch</span><span class="w"> </span><span class="k" data-group-id="7163761830-2">do</span><span class="w">
    </span><span class="n">exit</span><span class="p" data-group-id="7163761830-3">(</span><span class="ss">:timeout</span><span class="p" data-group-id="7163761830-3">)</span><span class="w">
  </span><span class="k" data-group-id="7163761830-2">catch</span><span class="w">
    </span><span class="ss">:exit</span><span class="p">,</span><span class="w"> </span><span class="ss">:timeout</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
      </span><span class="p" data-group-id="7163761830-4">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="ss">:timeout</span><span class="p" data-group-id="7163761830-4">}</span><span class="w">
  </span><span class="k" data-group-id="7163761830-2">end</span><span class="w">

  </span><span class="kd">def</span><span class="w"> </span><span class="nf">mismatched_catch</span><span class="w"> </span><span class="k" data-group-id="7163761830-5">do</span><span class="w">
    </span><span class="n">exit</span><span class="p" data-group-id="7163761830-6">(</span><span class="ss">:timeout</span><span class="p" data-group-id="7163761830-6">)</span><span class="w">
  </span><span class="k" data-group-id="7163761830-5">catch</span><span class="w">
    </span><span class="c1"># Since no clause matches, this catch will have no effect</span><span class="w">
    </span><span class="ss">:exit</span><span class="p">,</span><span class="w"> </span><span class="ss">:explosion</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
      </span><span class="p" data-group-id="7163761830-7">{</span><span class="ss">:error</span><span class="p">,</span><span class="w"> </span><span class="ss">:explosion</span><span class="p" data-group-id="7163761830-7">}</span><span class="w">
  </span><span class="k" data-group-id="7163761830-5">end</span><span class="w">
</span><span class="k" data-group-id="7163761830-1">end</span></code></pre><p>However, using <code class="inline">try/catch</code> is already uncommon and using it to catch exits is even rarer.</p><p><code class="inline">exit</code> signals are an important part of the fault tolerant system provided by the Erlang VM. Processes usually run under supervision trees which are themselves processes that listen to <code class="inline">exit</code> signals from the supervised processes. Once an <code class="inline">exit</code> signal is received, the supervision strategy kicks in and the supervised process is restarted.</p><p>It is exactly this supervision system that makes constructs like <code class="inline">try/catch</code> and <code class="inline">try/rescue</code> so uncommon in Elixir. Instead of rescuing an error, we'd rather &quot;fail fast&quot; since the supervision tree will guarantee our application will go back to a known initial state after the error.</p><h2 id="after" class="section-heading">
  <a href="#after" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">After</span>
</h2>
<p>Sometimes it's necessary to ensure that a resource is cleaned up after some action that could potentially raise an error. The <code class="inline">try/after</code> construct allows you to do that. For example, we can open a file and use an <code class="inline">after</code> clause to close it -- even if something goes wrong:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="p" data-group-id="6586589800-1">{</span><span class="ss">:ok</span><span class="p">,</span><span class="w"> </span><span class="n">file</span><span class="p" data-group-id="6586589800-1">}</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="nc">File</span><span class="o">.</span><span class="n">open</span><span class="p" data-group-id="6586589800-2">(</span><span class="s">&quot;sample&quot;</span><span class="p">,</span><span class="w"> </span><span class="p" data-group-id="6586589800-3">[</span><span class="ss">:utf8</span><span class="p">,</span><span class="w"> </span><span class="ss">:write</span><span class="p" data-group-id="6586589800-3">]</span><span class="p" data-group-id="6586589800-2">)</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="6586589800-4">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">IO</span><span class="o">.</span><span class="n">write</span><span class="p" data-group-id="6586589800-5">(</span><span class="n">file</span><span class="p">,</span><span class="w"> </span><span class="s">&quot;olá&quot;</span><span class="p" data-group-id="6586589800-5">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops, something went wrong&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="6586589800-4">after</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">File</span><span class="o">.</span><span class="n">close</span><span class="p" data-group-id="6586589800-6">(</span><span class="n">file</span><span class="p" data-group-id="6586589800-6">)</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="6586589800-4">end</span><span class="w">
</span><span class="gt">** (RuntimeError) oops, something went wrong</span></code></pre><p>The <code class="inline">after</code> clause will be executed regardless of whether or not the tried block succeeds. Note, however, that if a linked process exits,
this process will exit and the <code class="inline">after</code> clause will not get run. Thus <code class="inline">after</code> provides only a soft guarantee. Luckily, files in Elixir are also linked to the current processes and therefore they will always get closed if the current process crashes, independent of the
<code class="inline">after</code> clause. You will find the same to be true for other resources like ETS tables, sockets, ports and more.</p><p>Sometimes you may want to wrap the entire body of a function in a <code class="inline">try</code> construct, often to guarantee some code will be executed afterwards. In such cases, Elixir allows you to omit the <code class="inline">try</code> line:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="kd">defmodule</span><span class="w"> </span><span class="nc">RunAfter</span><span class="w"> </span><span class="k" data-group-id="3582093579-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="kd">def</span><span class="w"> </span><span class="nf">without_even_trying</span><span class="w"> </span><span class="k" data-group-id="3582093579-2">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;oops&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k" data-group-id="3582093579-2">after</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="nc">IO</span><span class="o">.</span><span class="n">puts</span><span class="w"> </span><span class="s">&quot;cleaning up!&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k" data-group-id="3582093579-2">end</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="3582093579-1">end</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="nc">RunAfter</span><span class="o">.</span><span class="n">without_even_trying</span><span class="w">
</span><span class="n">cleaning</span><span class="w"> </span><span class="n">up!</span><span class="w">
</span><span class="gt">** (RuntimeError) oops</span></code></pre><p>Elixir will automatically wrap the function body in a <code class="inline">try</code> whenever one of <code class="inline">after</code>, <code class="inline">rescue</code> or <code class="inline">catch</code> is specified.</p><h2 id="else" class="section-heading">
  <a href="#else" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Else</span>
</h2>
<p>If an <code class="inline">else</code> block is present, it will match on the results of the <code class="inline">try</code> block whenever the <code class="inline">try</code> block finishes without a throw or an error.</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="n">x</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="mi">2</span><span class="w">
</span><span class="mi">2</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="4123056445-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="mi">1</span><span class="w"> </span><span class="o">/</span><span class="w"> </span><span class="n">x</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4123056445-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="nc">ArithmeticError</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="ss">:infinity</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4123056445-1">else</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">y</span><span class="w"> </span><span class="ow">when</span><span class="w"> </span><span class="n">y</span><span class="w"> </span><span class="o">&lt;</span><span class="w"> </span><span class="mi">1</span><span class="w"> </span><span class="ow">and</span><span class="w"> </span><span class="n">y</span><span class="w"> </span><span class="o">&gt;</span><span class="w"> </span><span class="o">-</span><span class="mi">1</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="ss">:small</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="bp">_</span><span class="w"> </span><span class="o">-&gt;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="ss">:large</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4123056445-1">end</span><span class="w">
</span><span class="ss">:small</span></code></pre><p>Exceptions in the <code class="inline">else</code> block are not caught. If no pattern inside the <code class="inline">else</code> block matches, an exception will be raised; this exception is not caught by the current <code class="inline">try/catch/rescue/after</code> block.</p><h2 id="variables-scope" class="section-heading">
  <a href="#variables-scope" class="hover-link">
    <i class="ri-link-m" aria-hidden="true"></i>
  </a>
  <span class="text">Variables scope</span>
</h2>
<p>Similar to <code class="inline">case</code>, <code class="inline">cond</code>, <code class="inline">if</code> and other constructs in Elixir, variables defined inside <code class="inline">try/catch/rescue/after</code> blocks do not leak to the outer context. In other words, this code is invalid:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="4550260052-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;fail&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">what_happened</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ss">:did_not_raise</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4550260052-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="bp">_</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="n">what_happened</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ss">:rescued</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="4550260052-1">end</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="n">what_happened</span><span class="w">
</span><span class="gt">** (CompileError) undefined variable &quot;what_happened&quot;</span></code></pre><p>Instead, you should return the value of the <code class="inline">try</code> expression:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="n">what_happened</span><span class="w"> </span><span class="o">=</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="7675760873-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;fail&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="ss">:did_not_raise</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k" data-group-id="7675760873-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">    </span><span class="bp">_</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="ss">:rescued</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k" data-group-id="7675760873-1">end</span><span class="w">
</span><span class="gp unselectable">iex&gt; </span><span class="n">what_happened</span><span class="w">
</span><span class="ss">:rescued</span></code></pre><p>Furthermore, variables defined in the do-block of <code class="inline">try</code> are not available inside <code class="inline">rescue/after/else</code> either. This is because the <code class="inline">try</code> block may fail at any moment and therefore the variables may have never been bound in the first place. So this also isn't valid:</p><pre><code class="makeup elixir" translate="no"><span class="gp unselectable">iex&gt; </span><span class="k">try</span><span class="w"> </span><span class="k" data-group-id="2589823253-1">do</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="k">raise</span><span class="w"> </span><span class="s">&quot;fail&quot;</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="n">another_what_happened</span><span class="w"> </span><span class="o">=</span><span class="w"> </span><span class="ss">:did_not_raise</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="2589823253-1">rescue</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="w">  </span><span class="bp">_</span><span class="w"> </span><span class="o">-&gt;</span><span class="w"> </span><span class="n">another_what_happened</span><span class="w">
</span><span class="gp unselectable">...&gt; </span><span class="k" data-group-id="2589823253-1">end</span><span class="w">
</span><span class="gt">** (CompileError) undefined variable &quot;another_what_happened&quot;</span></code></pre><p>This finishes our introduction on <code class="inline">try</code>, <code class="inline">catch</code>, and <code class="inline">rescue</code>. You will find they are used less frequently in Elixir than in other languages. Next we will talk about a very important subject to Elixir developers: writing documentation.</p>
</div>

<div class="bottom-actions" id="bottom-actions">
  <div class="bottom-actions-item">

      <a href="sigils.html" class="bottom-actions-button" rel="prev">
        <span class="subheader">
          ← Previous Page
        </span>
        <span class="title">
Sigils
        </span>
      </a>

  </div>
  <div class="bottom-actions-item">

      <a href="writing-documentation.html" class="bottom-actions-button" rel="next">
        <span class="subheader">
          Next Page →
        </span>
        <span class="title">
Writing documentation
        </span>
      </a>

  </div>
</div>
    <footer class="footer">
      <p>

        <span class="line">
          <button class="a-main footer-button display-quick-switch" title="Search HexDocs packages">
            Search HexDocs
          </button>

            <a href="Elixir.epub" title="ePub version">
              Download ePub version
            </a>

        </span>
      </p>

      <p class="built-using">
        Built using
        <a href="https://github.com/elixir-lang/ex_doc" title="ExDoc" target="_blank" rel="help noopener" translate="no">ExDoc</a> (v0.34.2) for the

          <a href="https://elixir-lang.org" title="Elixir" target="_blank" translate="no">Elixir programming language</a>

      </p>

    </footer>
  </div>
</main>
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10.2.3/dist/mermaid.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    mermaid.initialize({
      startOnLoad: false,
      theme: document.body.className.includes("dark") ? "dark" : "default"
    });
    let id = 0;
    for (const codeEl of document.querySelectorAll("pre code.mermaid")) {
      const preEl = codeEl.parentElement;
      const graphDefinition = codeEl.textContent;
      const graphEl = document.createElement("div");
      const graphId = "mermaid-graph-" + id++;
      mermaid.render(graphId, graphDefinition).then(({svg, bindFunctions}) => {
        graphEl.innerHTML = svg;
        bindFunctions?.(graphEl);
        preEl.insertAdjacentElement("afterend", graphEl);
        preEl.remove();
      });
    }
  });
</script>

  </body>
</html>
